# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FuegoCli < Formula
  desc "A file-system based Go framework for APIs and websites"
  homepage "https://github.com/abdul-hamid-achik/fuego"
  version "0.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.5/fuego_0.3.5_darwin_amd64.tar.gz"
      sha256 "ed0320e28ad0d1bc4d44f32ce2128d538ccaf77d294751e94f512844165734df"

      def install
        bin.install "fuego"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.5/fuego_0.3.5_darwin_arm64.tar.gz"
      sha256 "2545e46ac46ef7709ff41376445136eb4fdea3407f5dd4bcd09d303c296d13dd"

      def install
        bin.install "fuego"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.5/fuego_0.3.5_linux_amd64.tar.gz"
      sha256 "47ce829cef35c1c5659055c039c4f6ff301777deae43e35288550a7fa484ce75"
      def install
        bin.install "fuego"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.5/fuego_0.3.5_linux_arm64.tar.gz"
      sha256 "9c16fcdc17b504283b741d434df991eb57e74d3128bc30e17364a69e8c5362bc"
      def install
        bin.install "fuego"
      end
    end
  end
end
