# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fuego < Formula
  desc "A file-system based Go framework for APIs and websites"
  homepage "https://github.com/abdul-hamid-achik/fuego"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.2/fuego_0.3.2_darwin_amd64.tar.gz"
      sha256 "8d709076557cd082c18166c5652b9dff1a252551e4444c7123d37442a30c9e6d"

      def install
        bin.install "fuego"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.2/fuego_0.3.2_darwin_arm64.tar.gz"
      sha256 "79a4ac683567b72e3b73b69d9cd42efa4df297218adc054343baca98200c31de"

      def install
        bin.install "fuego"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.2/fuego_0.3.2_linux_amd64.tar.gz"
      sha256 "062aed7d23919789413c8f5180bc89e5d979680998ac7dad9fadce4d411bb906"
      def install
        bin.install "fuego"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.2/fuego_0.3.2_linux_arm64.tar.gz"
      sha256 "533feb049c5a1fab7c34429de1e493a7a4448bbce6496ceaf0f18b77af55fc68"
      def install
        bin.install "fuego"
      end
    end
  end
end
