# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FuegoCli < Formula
  desc "A file-system based Go framework for APIs and websites"
  homepage "https://github.com/abdul-hamid-achik/fuego"
  version "0.3.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.8/fuego_0.3.8_darwin_amd64.tar.gz"
      sha256 "033832c732a56c80c0de81f34535d6426b5bf05f29e115d8f325ea47aa450566"

      def install
        bin.install "fuego"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.8/fuego_0.3.8_darwin_arm64.tar.gz"
      sha256 "a4fd5b9acf7265b9ae1ab635c2b92e8f20afcfd294a9c508bebd455ad5df049f"

      def install
        bin.install "fuego"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.8/fuego_0.3.8_linux_amd64.tar.gz"
      sha256 "091061c0bdd95294b0231288cd5e8b999b8b3507127a66ff4c6d6c388b42bd3a"
      def install
        bin.install "fuego"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v0.3.8/fuego_0.3.8_linux_arm64.tar.gz"
      sha256 "c212f58438492ae011866e480c34d358fbe9f4056dca1ae13b41aefba67dc628"
      def install
        bin.install "fuego"
      end
    end
  end
end
