# This file was generated by GoReleaser. DO NOT EDIT.
cask "fuego-cli" do
  name "fuego-cli"
  desc "A file-system based Go framework for APIs and websites"
  homepage "https://github.com/abdul-hamid-achik/fuego"
  version "0.7.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fuego"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_darwin_amd64.tar.gz"
      sha256 "83375158f6485c10a4ac59e42692cfe2948f4649836393d836e344d4baeccb6e"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_darwin_arm64.tar.gz"
      sha256 "17aa8dc1fd48910217c38d94445dc5f03f290d8fbf3509c27e0cbb254974028a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_linux_amd64.tar.gz"
      sha256 "d86445712fdf5f3e82c8b7985c1580f7108416bb5c2272be50196ef2760fca45"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_linux_arm64.tar.gz"
      sha256 "f5c403a586d2c853d49c16ae93e209f200c68afe121e079bb4a65ba88da257eb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fuego"]
    end
  end

  # No zap stanza required
end
