# This file was generated by GoReleaser. DO NOT EDIT.
cask "fuego-cli" do
  name "fuego-cli"
  desc "A file-system based Go framework for APIs and websites"
  homepage "https://github.com/abdul-hamid-achik/fuego"
  version "0.11.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fuego"

  on_macos do
    on_intel do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_darwin_amd64.tar.gz"
      sha256 "cbbdb303327dd1e608440104adbea88fb3170605b86a985aa60a87705a566c87"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_darwin_arm64.tar.gz"
      sha256 "8b6bfb7250d41f86ce6d73a240ef7de00ab261ebb0fe5bb5ebd93cec3fde5fb6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_linux_amd64.tar.gz"
      sha256 "9a50bb3a5d6e4d307062e09d92fa0fcad2091c589c3f2b09f208762ca3d04bf6"
    end
    on_arm do
      url "https://github.com/abdul-hamid-achik/fuego/releases/download/v#{version}/fuego_#{version}_linux_arm64.tar.gz"
      sha256 "1ed3019d01e0c0b8c75e90376fadc56fc6bf2b84c3b9321164bdd45f813c9cc7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fuego"]
    end
  end

  # No zap stanza required
end
